version: "3"
services:
  web-client:
    build: ./client
    ports:
      - 8080:3000
  bottle-neck:
    build: ./server
    stop_signal: SIGINT
    ports:
      - 5000:5000
  db:
    image: mongo:6.0.1
    user: "${DUID}:${DGID}"
    volumes:
      - ./mongo_data:/data/db
