version: "3"
services:
  bottle-neck:
    build: .
    volumes:
      - ./app_data:/bottle_neck/data
    ports:
      - 8080:80
  db:
    image: mongo:6.0.1
    volumes:
      - ./mongo_data:/data/db
