version: "3"
services:
  web-client:
    build: ./client
    ports:
      - 8080:3000
  bottle-neck:
    build: ./server
    volumes:
      - ./app_data:/bottle_neck/data
    ports:
      - 5000:5000
  db:
    image: mongo:6.0.1
    volumes:
      - ./mongo_data:/data/db
