version: "3"
services:
  web-client:
    build: ./client
    ports:
      - 8080:3000
  bottle-neck:
    build: .
    volumes:
      - ./data:/bottle_neck/data
    ports:
      - 5000:80
  db:
    image: mongo:6.0.1
